### ISSUE TITLE
Error on page refresh

### ISSUE THREAD

**Issue by paolodina** [EBfVince/Spaceship#5]
Hi and thanks for this awesome template, it's not been easy to find it.

I just noted that when a user is logged in and visit http://localhost:3000/app, and the page is refreshed, an error message appears (An error occurred with a link to the homepage). In dev console there is an error `GET http://localhost:3000/app 403 (Forbidden)`, but the user it still logged in because the login/logout button on the homepage shows Déconnexion.

![Screenshot_2020-07-13_02-38-24](https://user-images.githubusercontent.com/1157401/87260392-f6f92500-c4b1-11ea-8454-4bcb5199ad98.png)

Is there a solution to this problem?

**Comment by EBfVince** [comment]
Hi ! Thank you for your feedback, it gives me strength to keep going 💪🚀

### Problem

I tried to reproduce your problem but I didn't. But, I know that the problem occur cause to the **server side rendering**. 

### Explanations

The server tried to render a "secure" page. The [app page](https://github.com/EBfVince/Spaceship/blob/master/src/pages/app/index.vue#L39) (`/app`) uses a middleware [securePage.js](https://github.com/EBfVince/Spaceship/blob/master/src/middleware/securePage.js) witch requires the user to be connected to access the page. If he's not connected, the middleware return a [403 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403).

All looks good when we do all the actions client side. But what's happen when the **server** needs to render `/app` page ? The `securePage` middleware needs to check the **client** store to validate the render of the `/app` page. If the server do not have the client's store, the request will end with a 403 error like you did.

In our case, the server needs to have the client information before rendering the page. The trick is done thanks to the [Firebase Nuxt Plugin](https://firebase.nuxtjs.org/guide/options/#ssr) that manage the SSR render with authentification.

### Solutions

- I upgraded the dependencies. Probably it fixes your problem 🤷‍♂️
- You should wipe your cache, kill the page and retry

Let me know how it goes !

**Comment by paolodina** [comment]
Thank you Vincent, the fix solved the issue.  :tada: I owe you something.
